### ISSUE TITLE
How do we close the video room?

### ISSUE THREAD

**Issue by antranvn** [crossle/janus-gateway-android#1]
Hello

**Comment by antranvn** [comment]
When i close video room from MainActivity, there is error like this:
 _Activity has leaked IntentReceiver org.webrtc.NetworkMonitorAutoDetect@250a871 that was originally registered here. Are you missing a call to unregisterReceiver()?_
Could you help check it?

**Comment by crossle** [comment]
Should close video from the MainActivity release

**Comment by antranvn** [comment]
I already have some code when there is end call event:
`// Disconnect from remote resources, dispose of local resources, and exit.
    private void disconnectCall() {
        if (peerConnectionClient != null) {
            peerConnectionClient.close();
            peerConnectionClient = null;
        }
        releaseRenders();
        mWebSocketChannel.closeWebSocket();
        //finish();
    }
   private void releaseRenders() {
        if (remoteRender != null) {
            remoteRender.release();
            remoteRender = null;
        }
        if (localRender != null) {
            localRender.release();
            localRender = null;
        }
    }
`
I saw in the log it seems NetworkMonitoAutoDetect is not unregistered when finish MainActivity, but we do not register this broadcast in MainActivity.

**Comment by crossle** [comment]
The NetworkMonitoAutoDetect in webrtc internal register, i saw your close code, it's should ok

**Comment by antranvn** [comment]
Yeap, is there any way to avoid it, because we can not make the second video call, app automatically exit as soon as user accept video call.

**Comment by lyapple2008** [comment]
I also found this error. Have you found the solution for this error?

**Comment by lyapple2008** [comment]
I think we should close all PeerConnection in peerConnectionMap. 
```
for (Map.Entry<BigInteger, JanusConnection> entry: peerConnectionMap.entrySet()) {
      if (entry.getValue().peerConnection != null) {
          entry.getValue().peerConnection.dispose();
      }
 }
```

**Comment by antranvn** [comment]
What webrtc version are you using now ?

**Comment by lyapple2008** [comment]
This is not about the version of webrtc. You should close every peer connection when you save these peer connection in the variable, peerConnectionMap. in this example project. Otherwise, the PeerConnectionClient will not exist successfully.

**Comment by crossle** [comment]
@lyapple2008 Yes, should close all

**Comment by antranvn** [comment]
You are right @lyapple2008. Thank you both :)

**Comment by akbarattar3** [comment]
Its still crashing with some exceptions when doing above code
 A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x8af0d610 in tid 26834 (pool-1-thread-1)
this is crash

**Comment by pwjpj52** [comment]
you should alse disconnect websocet or you will not connect ice server
