### ISSUE TITLE
How to change the room id 

### ISSUE THREAD

**Issue by akbarattar3** [crossle/janus-gateway-android#10]
When I change the room id from 1234 to some other double , local and remote both are not working .Can you please help me thanks in advance

**Comment by crossle** [comment]
The room id is janus room id

**Comment by akbarattar3** [comment]
I need to change it ,can I change it ? but it is not working

**Comment by crossle** [comment]
Yes, you can

**Comment by akbarattar3** [comment]
if I change that from 1234 to some other its not working

**Comment by akbarattar3** [comment]
I did it myself
