### ISSUE TITLE
How to close the janusconnection 

### ISSUE THREAD

**Issue by akbarattar3** [crossle/janus-gateway-android#11]
app is crashing whenever I am closing the connection

**Comment by crossle** [comment]
https://github.com/crossle/janus-gateway-android/issues/1

**Comment by akbarattar3** [comment]
I tried that solution but it is not working it is crashing the application with below exception
A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x8af0d610 in tid 26834 (pool-1-thread-1)
this is crash
