### ISSUE TITLE
Its still crashing with some exceptions when doing above code

### ISSUE THREAD

**Issue by akbarattar3** [crossle/janus-gateway-android#12]
Its still crashing with some exceptions when doing above code
 A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x8af0d610 in tid 26834 (pool-1-thread-1)
this is crash

_Originally posted by @akbarattar3 in https://github.com/crossle/janus-gateway-android/issues/1#issuecomment-532630122_

**Comment by akbarattar3** [comment]
Its solved

**Comment by sajidjutt7** [comment]
How did you solved it?
