### ISSUE TITLE
janus display wrong orientation with front camera

### ISSUE THREAD

**Issue by fukemy** [crossle/janus-gateway-android#13]
Here is my camera when i display front camera in app

Here is the image when i view in Janus
 I have a lot of searching to fix this orientation problem, but still stuck, can you give me some advise plz

**Comment by fukemy** [comment]
after check log: I saw the result when get all camera
```
 device: Camera 0, Facing back, Orientation 90
 device: Camera 1, Facing front, Orientation 270
```

The front camera display as expected in my device, but when display in Janus it rotate 270 degrees like Orientation 270

**Comment by crossle** [comment]
Two phone also have the problem?

**Comment by fukemy** [comment]
thanks you for fast reply, i found the way to solve it 😄 , just remove orientation extension from sdp before setlocaldescription
```
final SessionDescription sdp = new SessionDescription(origSdp.type, origSdp.description.replace("3gpp:video-orientation", ""));
```
then janus will display origin video without orientation
