### ISSUE TITLE
Not able to see the remote video - Warning : Deprecated use of ‘listener’ ptype, update to the new ‘subscriber’ ASAP

### ISSUE THREAD

**Issue by sajidjutt7** [crossle/janus-gateway-android#18]
I have logged into my video using janus video room.
I am able to get connect to my janus server as i am getting logs from server about my user on janus server.
Here on mobile i am able to see my camera view on local render view but not getting remote render view.

with this warning in logs

onMessage{
       “janus”: “event”,
       “session_id”: 509610509862512312,
       “transaction”: “lBLNILwqvw2p”,
       “sender”: 2853941759229518,
       “plugindata”: {
          “plugin”: “janus.plugin.videoroom”,
          “data”: {
             “videoroom”: “attached”,
             “room”: 3456,
             “id”: 4668964347315315,
             “display”: “sajid1",
             “warning”: “Deprecated use of ‘listener’ ptype, update to the new ‘subscriber’ ASAP”
          }
       },

**Comment by JRaadPro** [comment]
Hello mates, have you fixed this issue ?

**Comment by mmj-dev-git** [comment]
anyone able to fix that issue?

**Comment by JRaadPro** [comment]
The issue has nothing to do with this warning. What's your problem exactly ? can you post something to be able to help ? @m-jayy

**Comment by sajidjutt7** [comment]
Yes i resolved this error. Sorry for not informing earlier.
By replacing "listener" with "subscriber" as  : 
Change this 👇 
body.putOpt("ptype", "listener");
To this 👇 
body.putOpt("ptype", "subscriber");
