### ISSUE TITLE
这个工程是不是没有中间件，例如PeerConnection

### ISSUE THREAD

**Issue by laoma634980838** [crossle/janus-gateway-android#2]
我下载了这个工程，但是找不到org.webrtc这个包，PeerConnection也在这个包里。请问是不是工程少文件了，还是我下载的不对？

**Comment by crossle** [comment]
在这里 https://github.com/crossle/janus-gateway-android/tree/master/app/libs

**Comment by laoma634980838** [comment]
找到了，非常感谢。我这边编译成功了，但是只显示自己端的视频，好像没有连接成功。怀疑是IceCandidate的问题，我这边是局域网，turn服务器一定要设置吗？log如下：
01-15 22:08:33.869 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: Create peer connection factory. Use video: true
01-15 22:08:33.869 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: Pereferred video codec: H264
01-15 22:08:33.869 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: Disable OpenSL ES audio even if device supports it
01-15 22:08:33.869 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: Enable built-in AEC if device supports it
01-15 22:08:33.869 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: Enable built-in AGC if device supports it
01-15 22:08:33.869 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: Enable built-in NS if device supports it
01-15 22:08:33.987 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: Peer connection factory created.
01-15 22:08:33.988 23184-23211/in.minewave.janusvideoroom I/org.webrtc.Logging: PCRTCClient: Capturing format: 360x480@20
01-15 22:08:33.988 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: PCConstraints: mandatory: [], optional: [DtlsSrtpKeyAgreement: true]
01-15 22:08:33.988 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: EGLContext: org.webrtc.EglBase14$Context@245a84c
01-15 22:08:33.998 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: Create peer connection.
01-15 22:08:34.005 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: Peer connection created.
01-15 22:08:34.016 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: Found video sender.
01-15 22:08:34.016 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: PC Create OFFER
01-15 22:08:34.018 23184-23215/in.minewave.janusvideoroom E/PCRTCClient: SDP on create success
01-15 22:08:34.018 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: Set local SDP from OFFER
01-15 22:08:34.026 23184-23215/in.minewave.janusvideoroom D/PCRTCClient: SignalingState: HAVE_LOCAL_OFFER
01-15 22:08:34.047 23184-23215/in.minewave.janusvideoroom D/PCRTCClient: IceGatheringState: GATHERING
01-15 22:08:34.047 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: Local SDP set succesfully
01-15 22:08:34.068 23184-23215/in.minewave.janusvideoroom D/PCRTCClient: SignalingState: STABLE
01-15 22:08:34.075 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: : CHECKING
01-15 22:08:34.076 23184-23211/in.minewave.janusvideoroom D/PCRTCClient: Remote SDP set succesfully
01-15 22:09:14.197 23184-23215/in.minewave.janusvideoroom D/PCRTCClient: IceGatheringState: COMPLETE

**Comment by crossle** [comment]
是要设置的
