### ISSUE TITLE
Java janus desktop app

### ISSUE THREAD

**Issue by kinsleykajiva** [crossle/janus-gateway-android#24]
hi , have you ever looked into this https://github.com/devopvoid/webrtc-java and possibly have a desktop implementation maybe using JavaFX or swing ?

**Comment by crossle** [comment]
Yes, the code should support Java desktop.

**Comment by kinsleykajiva** [comment]
yes, i have tried it out i am having issues with implementation for example media constraints, getting ice candidates to send based on the desktop requirements.
