### ISSUE TITLE
can you implement an audio bridge demo ?

### ISSUE THREAD

**Issue by AhmedHumk** [crossle/janus-gateway-android#25]
i am trying to create audio room like in janus audio bridge demo but not sure where to start

**Comment by crossle** [comment]
If you use audio, I think you can try https://github.com/mixinnetwork/kraken.fm

**Comment by AhmedHumk** [comment]
janus already implemented audio room 

https://janus.conf.meetecho.com/audiobridgetest.html

i am trying to use your example to mimic the same solution in android studio without luck.
