### ISSUE TITLE
don't found org.webrtc

### ISSUE THREAD

**Issue by vit1967** [crossle/janus-gateway-android#5]
I trying to implement this janus for Android native app(not browser)  in AndroidStudio and try make. While compile i see many errors some..
work/android/VPhoneChatAgent/Janus/janus-gateway-android-master/app/src/main/java/computician/janusclient/EchoTest.java	
error: package org.webrtc does not exist	
error: package org.webrtc does not exist	
error: package org.webrtc does not exist	
error: package VideoRenderer does not exist	
error: package PeerConnection does not exist	
error: cannot find symbol class MediaStream	
error: cannot find symbol class VideoRenderer	
error: cannot find symbol variable VideoRendererGui	
error: package VideoRendererGui does not exist	
error: package VideoRendererGui does not exist	
../../../../../../../../../../../../../../../../../work/android/VPhoneChatAgent/Janus/janus-gateway-android-master/app/src/main/java/computician/janusclient/JanusActivity.java	
error: package org.webrtc does not exist	
error: package VideoRenderer does not exist	
error: cannot find symbol variable VideoRendererGui	
error: package VideoRendererGui does not exist	
error: package VideoRendererGui does not exist	
../../../../../../../../../../../../../../../../../work/android/VPhoneChatAgent/Janus/janus-gateway-android-master/app/src/main/java/computician/janusclient/VideoRoomTest.java	
error: package org.webrtc does not exist	
error: package org.webrtc does not exist	
error: package VideoRenderer does not exist	
error: package VideoRenderer does not exist	
error: package VideoRenderer does not exist	
error: cannot find symbol class MediaStream	
error: cannot find symbol class MediaStream	
error: package PeerConnection does not exist	
error: cannot find symbol class VideoRenderer	
error: cannot find symbol class VideoRenderer	

..All this from not found module
org.webrtc

Whan i try search this modul in poject dependence i don't see any, that can resolve this dependence.
Can you help me?

**Comment by crossle** [comment]
The dependence is here https://github.com/crossle/janus-gateway-android/tree/master/app/libs
