### ISSUE TITLE
I am not able to get the remote video .I only able to see local video 

### ISSUE THREAD

**Issue by akbarattar3** [crossle/janus-gateway-android#7]
Please let me know if I am doing anything wrong

**Comment by crossle** [comment]
Plz set turn server if your relay the video

**Comment by akbarattar3** [comment]
@crossle we have turn server but in code there is no where space to set it

**Comment by crossle** [comment]
https://github.com/crossle/janus-gateway-android/blob/master/app/src/main/java/in/minewave/janusvideoroom/PeerConnectionClient.java#L376

**Comment by akbarattar3** [comment]
Thanks but when I added the turn server its giving me this error 
"java.lang.NumberFormatException: Invalid BigInteger: "

**Comment by akbarattar3** [comment]
And this is the log if that helps you to debug thanks in advance 

"Duration: 4000 ms. Frames received: 100. Dropped: 0. Rendered: 100. Render fps: 25.0. Average render time: 2773 μs. Average swapBuffer time: 2265 μs.
 Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: 0.0. Average render time: NA. Average swapBuffer time: NA."

**Comment by akbarattar3** [comment]
@crossle can you please suggest

**Comment by akbarattar3** [comment]
Issue is solved now thanks
