### ISSUE TITLE
Can I add multiple remote users ?

### ISSUE THREAD

**Issue by akbarattar3** [crossle/janus-gateway-android#8]
Can we add multiple remote users for this ?

**Comment by crossle** [comment]
Yes

**Comment by akbarattar3** [comment]
But in code there is no option to add multiple remote users

**Comment by crossle** [comment]
Other users can join same room, it's support.

**Comment by akbarattar3** [comment]
yeah same room but in app its showing only 2 video views ,and 2nd remote is overlapping on 1st remote

**Comment by crossle** [comment]
oh, this just a example, you need add your view to the Activity

**Comment by akbarattar3** [comment]
Ok it is working now
