### ISSUE TITLE
Remote video not restarting 

### ISSUE THREAD

**Issue by akbarattar3** [crossle/janus-gateway-android#9]
When remote video started but when I stop and restart it then video on application is hung up.It is not started again .Please suggest

**Comment by akbarattar3** [comment]
getting this error "ICE connection failed."

**Comment by akbarattar3** [comment]
Please help with this , Thanks in advance

**Comment by akbarattar3** [comment]
also getting this error 
 # Fatal error in ../../../home/webrtc/src/webrtc/base/event_tracer.cc, line 372
    # last system error: 11
    # Check failed: rtc::AtomicOps::CompareAndSwapPtr( &g_event_logger, static_cast<EventLogger*>(nullptr), new EventLogger()) == nullptr
    # 
    #

**Comment by crossle** [comment]
WebRTC bug? or you can check where hung up?

**Comment by akbarattar3** [comment]
The scenario is when remote video stopped and in local video it will show a black screen but when I restart the remote video then in app remote video wont start .Then kill the app then it is crashing

**Comment by akbarattar3** [comment]
@crossle did you able to reproduce this issue ?>

**Comment by akbarattar3** [comment]
@crossle atleast tell me why this exception throws "ICE connection failed.".I will be very thankful

**Comment by akbarattar3** [comment]
sir please reply its very urgent

**Comment by akbarattar3** [comment]
I solved this issue by myself Thanks

**Comment by arshadbinhamza** [comment]
> I solved this issue by myself Thanks

I am also facing same problem,Could you please let us know here how did you resolved, Thanks in advance
